import { Radio } from "@ocean-ui/ocean";
import * as contracts from "../contracts";

export default function CoverPage({ contract, setContract }) {
  return (
    <>
      <h1>RED Token Generator</h1>
      <p>
        RED Token Generator allows you to deploy your own smart contracts and
        tokens without writing a single line of code.
      </p>
      <p>
        <strong>Notice:</strong> Red chain solutions is not liable for any
        issues that may arise from the contracts and tokens generated by this
        tool.
      </p>
      <h1>Choose a contract type:</h1>
      <div id="contract-choice" onChange={(e) => setContract(e.target.value)}>
        {Object.keys(contracts).map((_contract, i) => (
          <Radio
            key={i}
            value={_contract}
            groupName="contract-choice"
            checked={contract === _contract}
          >
            {contracts[_contract].name}
          </Radio>
        ))}
      </div>
    </>
  );
}
